# Generated by Django 5.0.6 on 2026-05-23 10:59

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True, default=1)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalProduct",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True, default=1)),
                ("name", models.CharField(max_length=300)),
                ("sku", models.CharField(db_index=True, max_length=100)),
                ("barcode", models.CharField(blank=True, db_index=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "Pieces"),
                            ("kg", "Kilograms"),
                            ("litre", "Litres"),
                            ("metre", "Metres"),
                            ("sq_metre", "Square Metres"),
                            ("box", "Box"),
                            ("dozen", "Dozen"),
                            ("bundle", "Bundle"),
                        ],
                        default="pcs",
                        max_length=20,
                    ),
                ),
                ("cost_price_paise", models.BigIntegerField(default=0)),
                ("sell_price_paise", models.BigIntegerField(default=0)),
                (
                    "low_stock_threshold",
                    models.DecimalField(decimal_places=3, default=Decimal("0.000"), max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.category",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical product",
                "verbose_name_plural": "historical products",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True, default=1)),
                ("name", models.CharField(max_length=300)),
                ("sku", models.CharField(db_index=True, max_length=100, unique=True)),
                ("barcode", models.CharField(blank=True, db_index=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "Pieces"),
                            ("kg", "Kilograms"),
                            ("litre", "Litres"),
                            ("metre", "Metres"),
                            ("sq_metre", "Square Metres"),
                            ("box", "Box"),
                            ("dozen", "Dozen"),
                            ("bundle", "Bundle"),
                        ],
                        default="pcs",
                        max_length=20,
                    ),
                ),
                ("cost_price_paise", models.BigIntegerField(default=0)),
                ("sell_price_paise", models.BigIntegerField(default=0)),
                (
                    "low_stock_threshold",
                    models.DecimalField(decimal_places=3, default=Decimal("0.000"), max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True, default=1)),
                (
                    "stock_qty",
                    models.DecimalField(decimal_places=3, default=Decimal("0.000"), max_digits=10),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inventories",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True, default=1)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("opening", "Opening Stock"),
                            ("stock_in", "Stock In"),
                            ("sale", "Sale"),
                            ("return", "Return"),
                            ("adjustment", "Adjustment"),
                            ("damage", "Damage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("qty_change", models.DecimalField(decimal_places=3, max_digits=10)),
                ("qty_after", models.DecimalField(decimal_places=3, max_digits=10)),
                ("cost_price_paise", models.BigIntegerField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
