# Generated by Django 5.0.6 on 2026-06-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_historicalproduct_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="image",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
