# Hand-written (not generated by `makemigrations`) — this environment has no
# network access to install Django to run it. The change is metadata-only
# (adds a `validators` entry; no column/type change), so it's safe to author
# directly. Run `python manage.py makemigrations --check` after `pip install
# -r requirements/dev.txt` to confirm this matches what Django would have
# generated — see docs/PHASE_13_SECURITY_FIXES.md.

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_historicalproduct_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                validators=[apps.catalog.models.validate_product_image],
            ),
        ),
    ]
