# Generated by Django 5.2.15 on 2026-09-08 09:26

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_image_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="image",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[apps.catalog.models.validate_product_image],
            ),
        ),
    ]
