# Hand-written (not generated by `makemigrations`) — this environment has no
# network access to install Django to run it (confirmed again: PyPI still
# returns 403 through this session's proxy). Same situation as the two
# migrations from the Phase 13 security pass — see docs/PHASE_13_SECURITY_FIXES.md
# for how that one was verified. Run `python manage.py makemigrations --check
# --dry-run` after `pip install -r requirements/dev.txt` to confirm this fully
# matches what Django would have generated — see docs/FEATURE_DESIGN_SUPPLIERS.md
# and the testing guide for the full verification steps.
#
# Two operations, both additive:
#   1. CreateModel Supplier — a new table, nothing else affected.
#   2. AddField StockMovement.supplier — a new nullable FK column. Existing
#      rows all get NULL, which is the correct, honest answer for stock
#      recorded before this feature existed.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_historicalproduct_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.IntegerField(db_index=True, default=1)),
                ("name", models.CharField(max_length=200)),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="catalog.supplier",
            ),
        ),
    ]
