# Generated by Django 5.0.6 on 2026-06-04 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("sale_created", "Sale Created"),
                            ("sale_voided", "Sale Voided"),
                            ("return_created", "Return Processed"),
                            ("stock_in", "Stock Added"),
                            ("setting_changed", "Setting Changed"),
                            ("shift_opened", "Shift Opened"),
                            ("shift_closed", "Shift Closed"),
                            ("customer_created", "Customer Created"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.CharField(blank=True, max_length=45)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("tenant_id", models.IntegerField(db_index=True, default=1)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
