# Generated by Django 5.0.6 on 2026-09-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
