# Generated by Django 5.0.6 on 2026-09-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('sale_created', 'Sale Created'), ('sale_voided', 'Sale Voided'), ('return_created', 'Return Processed'), ('stock_in', 'Stock Added'), ('setting_changed', 'Setting Changed'), ('shift_opened', 'Shift Opened'), ('shift_closed', 'Shift Closed'), ('customer_created', 'Customer Created'), ('login_failed', 'Failed Login Attempt'), ('user_created', 'Staff Account Created'), ('user_updated', 'Staff Account Changed'), ('password_reset', 'Password Reset by Owner'), ('password_changed', 'Password Changed'), ('tax_overridden', 'Tax Changed on a Bill'), ('product_archived', 'Product Archived'), ('product_deleted', 'Product Deleted'), ('quotation_created', 'Quotation Created'), ('quotation_converted', 'Quotation Became a Sale')], db_index=True, max_length=30),
        ),
    ]
