# Hand-written (not generated by `makemigrations`) — this environment has no
# network access to install Django to run it. The change is metadata-only
# (an added `choices` option; no column/type change), so it's safe to author
# directly. Run `python manage.py makemigrations --check` after `pip install
# -r requirements/dev.txt` to confirm this matches what Django would have
# generated — see docs/PHASE_13_SECURITY_FIXES.md.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('sale_created', 'Sale Created'), ('sale_voided', 'Sale Voided'), ('return_created', 'Return Processed'), ('stock_in', 'Stock Added'), ('setting_changed', 'Setting Changed'), ('shift_opened', 'Shift Opened'), ('shift_closed', 'Shift Closed'), ('customer_created', 'Customer Created'), ('login_failed', 'Failed Login Attempt'), ('login_locked', 'Login Locked Out'), ('user_created', 'Staff Account Created'), ('user_updated', 'Staff Account Changed'), ('password_reset', 'Password Reset by Owner'), ('password_changed', 'Password Changed'), ('tax_overridden', 'Tax Changed on a Bill'), ('product_archived', 'Product Archived'), ('product_deleted', 'Product Deleted'), ('quotation_created', 'Quotation Created'), ('quotation_converted', 'Quotation Became a Sale')], db_index=True, max_length=30),
        ),
    ]
