# Generated by Django 5.0.6 on 2026-08-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0003_default_receipt_template"),
        ("config", "0005_receipt_page_format_setting"),
    ]

    operations = []
