# Generated by Django 5.0.6 on 2026-09-05 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_outstanding_paise_paymentreceived'),
        ('sales', '0007_alter_saleitemserial_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True, default=1)),
                ('kind', models.CharField(choices=[('sale', 'Credit sale'), ('payment', 'Payment received'), ('return', 'Return'), ('void', 'Sale voided'), ('adjustment', 'Manual adjustment'), ('opening', 'Opening balance')], max_length=20)),
                ('delta_paise', models.BigIntegerField()),
                ('balance_after_paise', models.BigIntegerField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='customers.customer')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='customers.paymentreceived')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to='sales.sale')),
            ],
            options={
                'verbose_name_plural': 'credit ledger entries',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='customers_c_custome_28b844_idx')],
            },
        ),
    ]
