# Generated by Django 5.0.6 on 2026-09-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_backfill_credit_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit_paise',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
