# Generated by Django 5.0.6 on 2026-09-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_credit_limit_paise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditledgerentry',
            name='kind',
            field=models.CharField(choices=[('sale', 'Credit sale'), ('installation', 'Installation charge on credit'), ('payment', 'Payment received'), ('return', 'Return'), ('void', 'Sale voided'), ('adjustment', 'Manual adjustment'), ('opening', 'Opening balance')], max_length=20),
        ),
    ]
