# Generated by Django 5.0.6 on 2026-09-04 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_sale_return_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleItemSerial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("serial", models.CharField(db_index=True, max_length=255)),
                ("warranty_months", models.IntegerField(blank=True, null=True)),
                (
                    "sale_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serials",
                        to="sales.saleitem",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("sale_item", "serial")},
            },
        ),
    ]
