# Generated by Django 5.0.6, with a defensive dedupe added by hand.

from django.db import migrations, models


def dedupe_serials(apps, schema_editor):
    """
    A serial identifies one physical unit. Uniqueness used to be scoped to the
    sale line, so the same serial could exist on many invoices. Any such rows
    must go before the global constraint can be applied.

    The earliest row wins — that is the sale that actually shipped the unit.
    """
    SaleItemSerial = apps.get_model("sales", "SaleItemSerial")
    seen, doomed = set(), []
    for pk, serial in SaleItemSerial.objects.order_by("id").values_list("id", "serial"):
        key = (serial or "").strip().lower()
        if key in seen:
            doomed.append(pk)
        else:
            seen.add(key)
    if doomed:
        SaleItemSerial.objects.filter(pk__in=doomed).delete()
        print(f"  removed {len(doomed)} duplicate serial row(s)")


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_alter_payment_method_alter_payment_sale"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="saleitemserial",
            unique_together=set(),
        ),
        migrations.RunPython(dedupe_serials, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="saleitemserial",
            constraint=models.UniqueConstraint(fields=("serial",), name="uniq_serial_global"),
        ),
    ]
