# Generated by Django 5.0.6 on 2026-09-05 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_saleitemserial_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paise',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_paid_paise',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale'),
        ),
    ]
