# Generated by Django 5.0.6 on 2026-09-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_backfill_payment_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='installation_note',
            field=models.CharField(blank=True, help_text='Who did the installation, or what the labour was for.', max_length=200),
        ),
        migrations.AddField(
            model_name='sale',
            name='installation_paise',
            field=models.BigIntegerField(default=0),
        ),
    ]
