# Generated by Django 5.0.6 on 2026-09-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_sale_installation_note_sale_installation_paise'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tax_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
