# Generated by Django 5.0.6 on 2026-09-06 03:22

import apps.sales.quotations
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_historicalproduct_image'),
        ('customers', '0006_alter_creditledgerentry_kind'),
        ('sales', '0012_backfill_tax_pct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True, default=1)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tax_number', models.CharField(blank=True, help_text='NTN / STRN', max_length=100)),
                ('footer', models.TextField(blank=True, help_text='Printed under the totals.')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True, default=1)),
                ('number', models.CharField(db_index=True, default=apps.sales.quotations._temp_number, max_length=50, unique=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('customer_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('valid_days', models.PositiveIntegerField(default=15, help_text='Printed on the quotation. Stops a January price being held to in March.')),
                ('subtotal_paise', models.BigIntegerField(default=0)),
                ('discount_paise', models.BigIntegerField(default=0)),
                ('tax_paise', models.BigIntegerField(default=0)),
                ('tax_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('installation_paise', models.BigIntegerField(default=0)),
                ('installation_note', models.CharField(blank=True, max_length=200)),
                ('total_paise', models.BigIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_quotation', to='sales.sale')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='customers.customer')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='sales.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('unit_price_paise', models.BigIntegerField(default=0)),
                ('discount_paise', models.BigIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='catalog.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quotation')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
